#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XAM_Trial_1.Resource", IsApplication=true)]

namespace XAM_Trial_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Charts.Resource.Animation.Fadein = global::XAM_Trial_1.Resource.Animation.Fadein;
			global::Com.Syncfusion.Charts.Resource.Animation.Fadeout = global::XAM_Trial_1.Resource.Animation.Fadeout;
			global::Com.Syncfusion.Charts.Resource.Animation.Scale_in = global::XAM_Trial_1.Resource.Animation.Scale_in;
			global::Com.Syncfusion.Charts.Resource.Animation.Scale_out = global::XAM_Trial_1.Resource.Animation.Scale_out;
			global::Com.Syncfusion.Charts.Resource.Id.annotationLayout = global::XAM_Trial_1.Resource.Id.annotationLayout;
			global::Com.Syncfusion.Charts.Resource.Id.axisLayout = global::XAM_Trial_1.Resource.Id.axisLayout;
			global::Com.Syncfusion.Charts.Resource.Id.bottom_labels = global::XAM_Trial_1.Resource.Id.bottom_labels;
			global::Com.Syncfusion.Charts.Resource.Id.chartBehaviorLayout = global::XAM_Trial_1.Resource.Id.chartBehaviorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.chartLegendScrollView = global::XAM_Trial_1.Resource.Id.chartLegendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.content = global::XAM_Trial_1.Resource.Id.content;
			global::Com.Syncfusion.Charts.Resource.Id.dataMarkerLayout = global::XAM_Trial_1.Resource.Id.dataMarkerLayout;
			global::Com.Syncfusion.Charts.Resource.Id.gridLineLayout = global::XAM_Trial_1.Resource.Id.gridLineLayout;
			global::Com.Syncfusion.Charts.Resource.Id.gridLinesLayout = global::XAM_Trial_1.Resource.Id.gridLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.iconView = global::XAM_Trial_1.Resource.Id.iconView;
			global::Com.Syncfusion.Charts.Resource.Id.label = global::XAM_Trial_1.Resource.Id.label;
			global::Com.Syncfusion.Charts.Resource.Id.legendHeader = global::XAM_Trial_1.Resource.Id.legendHeader;
			global::Com.Syncfusion.Charts.Resource.Id.legendItemsLayout = global::XAM_Trial_1.Resource.Id.legendItemsLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendLayout = global::XAM_Trial_1.Resource.Id.legendLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendScrollView = global::XAM_Trial_1.Resource.Id.legendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.legendViewGroup = global::XAM_Trial_1.Resource.Id.legendViewGroup;
			global::Com.Syncfusion.Charts.Resource.Id.rootLayout = global::XAM_Trial_1.Resource.Id.rootLayout;
			global::Com.Syncfusion.Charts.Resource.Id.seriesLayout = global::XAM_Trial_1.Resource.Id.seriesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.stripLinesLayout = global::XAM_Trial_1.Resource.Id.stripLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.technicalIndicatorLayout = global::XAM_Trial_1.Resource.Id.technicalIndicatorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.thumbLayout = global::XAM_Trial_1.Resource.Id.thumbLayout;
			global::Com.Syncfusion.Charts.Resource.Id.titleLayout = global::XAM_Trial_1.Resource.Id.titleLayout;
			global::Com.Syncfusion.Charts.Resource.Id.top_labels = global::XAM_Trial_1.Resource.Id.top_labels;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_layout = global::XAM_Trial_1.Resource.Layout.chart_layout;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend = global::XAM_Trial_1.Resource.Layout.chart_legend;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend_item = global::XAM_Trial_1.Resource.Layout.chart_legend_item;
			global::Com.Syncfusion.Charts.Resource.Layout.range_navigator_layout = global::XAM_Trial_1.Resource.Layout.range_navigator_layout;
			global::Com.Syncfusion.Charts.Resource.String.q = global::XAM_Trial_1.Resource.String.q;
			global::Com.Syncfusion.Charts.Resource.String.quarter = global::XAM_Trial_1.Resource.String.quarter;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_close_label = global::XAM_Trial_1.Resource.String.sfchart_close_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_high_label = global::XAM_Trial_1.Resource.String.sfchart_high_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_low_label = global::XAM_Trial_1.Resource.String.sfchart_low_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_open_label = global::XAM_Trial_1.Resource.String.sfchart_open_label;
			global::Com.Syncfusion.Charts.Resource.String.w = global::XAM_Trial_1.Resource.String.w;
			global::Com.Syncfusion.Charts.Resource.String.week = global::XAM_Trial_1.Resource.String.week;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int Fadein = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Fadeout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MyAnimation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Scale_in = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Scale_out = 2131034116;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f010010
			public const int font = 2130771984;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderAuthority = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderCerts = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderFetchStrategy = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchTimeout = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderPackage = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderQuery = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int fontStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int fontWeight = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0a0006
			public const int accent = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_action_color_filter = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_icon_bg_color = 2131361793;
			
			// aapt resource value: 0x7f0a0004
			public const int primary = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int primaryDark = 2131361797;
			
			// aapt resource value: 0x7f0a0002
			public const int ripple_material_light = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int secondary_text_default_material_light = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int splash_background = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int window_background = 2131361799;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000a
			public const int compat_button_inset_horizontal_material = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int compat_button_inset_vertical_material = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int compat_button_padding_horizontal_material = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int compat_button_padding_vertical_material = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int compat_control_corner_material = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int fastscroll_default_thickness = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fastscroll_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fastscroll_minimum_range = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int item_touch_helper_swipe_escape_velocity = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int notification_action_icon_size = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int notification_action_text_size = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_big_circle_margin = 2131099665;
			
			// aapt resource value: 0x7f060007
			public const int notification_content_margin_start = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int notification_large_icon_height = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_large_icon_width = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int notification_main_column_padding_top = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int notification_media_narrow_margin = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int notification_right_icon_size = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int notification_right_side_padding_top = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int notification_small_icon_background_padding = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int notification_small_icon_size_as_large = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int notification_subtext_size = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int notification_top_pad = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int notification_top_pad_large_text = 2131099673;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_template_icon_low_bg = 2130837517;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splashscreen = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070031
			public const int account = 2131165233;
			
			// aapt resource value: 0x7f07003d
			public const int action_container = 2131165245;
			
			// aapt resource value: 0x7f070049
			public const int action_divider = 2131165257;
			
			// aapt resource value: 0x7f07003e
			public const int action_image = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int action_text = 2131165247;
			
			// aapt resource value: 0x7f07004a
			public const int actions = 2131165258;
			
			// aapt resource value: 0x7f070016
			public const int annotationLayout = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int async = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int axisLayout = 2131165203;
			
			// aapt resource value: 0x7f070021
			public const int big3 = 2131165217;
			
			// aapt resource value: 0x7f070008
			public const int blocking = 2131165192;
			
			// aapt resource value: 0x7f07004d
			public const int bottom_labels = 2131165261;
			
			// aapt resource value: 0x7f070015
			public const int chartBehaviorLayout = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int chartLegendScrollView = 2131165209;
			
			// aapt resource value: 0x7f070048
			public const int chronometer = 2131165256;
			
			// aapt resource value: 0x7f07004e
			public const int content = 2131165262;
			
			// aapt resource value: 0x7f070011
			public const int dataMarkerLayout = 2131165201;
			
			// aapt resource value: 0x7f070024
			public const int djiaCurPrice = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int djiaNetChange = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int djiaPercentChange = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int djiaSpark = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int djiaTicker = 2131165218;
			
			// aapt resource value: 0x7f070009
			public const int forever = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int gridLineLayout = 2131165198;
			
			// aapt resource value: 0x7f07004f
			public const int gridLinesLayout = 2131165263;
			
			// aapt resource value: 0x7f070041
			public const int icon = 2131165249;
			
			// aapt resource value: 0x7f07001c
			public const int iconView = 2131165212;
			
			// aapt resource value: 0x7f07004b
			public const int icon_group = 2131165259;
			
			// aapt resource value: 0x7f070044
			public const int info = 2131165252;
			
			// aapt resource value: 0x7f07000a
			public const int italic = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_previous_elevation = 2131165184;
			
			// aapt resource value: 0x7f07001d
			public const int label = 2131165213;
			
			// aapt resource value: 0x7f070018
			public const int legendHeader = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int legendItemsLayout = 2131165211;
			
			// aapt resource value: 0x7f070014
			public const int legendLayout = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int legendScrollView = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int legendViewGroup = 2131165207;
			
			// aapt resource value: 0x7f070001
			public const int line1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int line3 = 2131165186;
			
			// aapt resource value: 0x7f070020
			public const int loginBtn = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int nasdaqCurPrice = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int nasdaqNetChange = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int nasdaqPercentChange = 2131165227;
			
			// aapt resource value: 0x7f070028
			public const int nasdaqSpark = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int nasdaqTicker = 2131165223;
			
			// aapt resource value: 0x7f07003c
			public const int news = 2131165244;
			
			// aapt resource value: 0x7f07000b
			public const int normal = 2131165195;
			
			// aapt resource value: 0x7f070046
			public const int notification_background = 2131165254;
			
			// aapt resource value: 0x7f070042
			public const int notification_main_column = 2131165250;
			
			// aapt resource value: 0x7f070040
			public const int notification_main_column_container = 2131165248;
			
			// aapt resource value: 0x7f07001f
			public const int password = 2131165215;
			
			// aapt resource value: 0x7f070033
			public const int posChart = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int posNetProfit = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int posPercentProfit = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int position = 2131165234;
			
			// aapt resource value: 0x7f070036
			public const int positions = 2131165238;
			
			// aapt resource value: 0x7f070045
			public const int right_icon = 2131165253;
			
			// aapt resource value: 0x7f070043
			public const int right_side = 2131165251;
			
			// aapt resource value: 0x7f07000c
			public const int rootLayout = 2131165196;
			
			// aapt resource value: 0x7f070037
			public const int search = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int searchChange = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int searchChart = 2131165243;
			
			// aapt resource value: 0x7f070039
			public const int searchPrice = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int searchTicker = 2131165240;
			
			// aapt resource value: 0x7f070010
			public const int seriesLayout = 2131165200;
			
			// aapt resource value: 0x7f07002e
			public const int spCurPrice = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int spNetChange = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int spPercentChange = 2131165232;
			
			// aapt resource value: 0x7f07002d
			public const int spSpark = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int spTicker = 2131165228;
			
			// aapt resource value: 0x7f07000f
			public const int stripLinesLayout = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int tag_transition_group = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int technicalIndicatorLayout = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int text = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int text2 = 2131165189;
			
			// aapt resource value: 0x7f070050
			public const int thumbLayout = 2131165264;
			
			// aapt resource value: 0x7f070047
			public const int time = 2131165255;
			
			// aapt resource value: 0x7f070006
			public const int title = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int titleLayout = 2131165197;
			
			// aapt resource value: 0x7f07004c
			public const int top_labels = 2131165260;
			
			// aapt resource value: 0x7f07001e
			public const int userID = 2131165214;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0000
			public const int status_bar_notification_info_maxnum = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int chart_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int chart_legend = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int chart_legend_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_action_tombstone = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_custom_big = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_icon_group = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_part_chronometer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_part_time = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int range_navigator_layout = 2130968587;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080009
			public const int app_name = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int default_search_ticker = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int q = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int quarter = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int sfchart_close_label = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int sfchart_high_label = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int sfchart_low_label = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int sfchart_open_label = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int w = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int week = 2131230723;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0009
			public const int MainTheme = 2131427337;
			
			// aapt resource value: 0x7f0b0007
			public const int SplashBase = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int SplashTheme = 2131427336;
			
			// aapt resource value: 0x7f0b0000
			public const int TextAppearance_Compat_Notification = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int TextAppearance_Compat_Notification_Info = 2131427329;
			
			// aapt resource value: 0x7f0b0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131427334;
			
			// aapt resource value: 0x7f0b0002
			public const int TextAppearance_Compat_Notification_Time = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int TextAppearance_Compat_Notification_Title = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int Widget_Compat_NotificationActionContainer = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int Widget_Compat_NotificationActionText = 2131427333;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
