#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XAM_Trial_1.Resource", IsApplication=true)]

namespace XAM_Trial_1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Charts.Resource.Animation.Fadein = global::XAM_Trial_1.Resource.Animation.Fadein;
			global::Com.Syncfusion.Charts.Resource.Animation.Fadeout = global::XAM_Trial_1.Resource.Animation.Fadeout;
			global::Com.Syncfusion.Charts.Resource.Animation.Scale_in = global::XAM_Trial_1.Resource.Animation.Scale_in;
			global::Com.Syncfusion.Charts.Resource.Animation.Scale_out = global::XAM_Trial_1.Resource.Animation.Scale_out;
			global::Com.Syncfusion.Charts.Resource.Id.annotationLayout = global::XAM_Trial_1.Resource.Id.annotationLayout;
			global::Com.Syncfusion.Charts.Resource.Id.axisLayout = global::XAM_Trial_1.Resource.Id.axisLayout;
			global::Com.Syncfusion.Charts.Resource.Id.bottom_labels = global::XAM_Trial_1.Resource.Id.bottom_labels;
			global::Com.Syncfusion.Charts.Resource.Id.chartBehaviorLayout = global::XAM_Trial_1.Resource.Id.chartBehaviorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.chartLegendScrollView = global::XAM_Trial_1.Resource.Id.chartLegendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.content = global::XAM_Trial_1.Resource.Id.content;
			global::Com.Syncfusion.Charts.Resource.Id.dataMarkerLayout = global::XAM_Trial_1.Resource.Id.dataMarkerLayout;
			global::Com.Syncfusion.Charts.Resource.Id.gridLineLayout = global::XAM_Trial_1.Resource.Id.gridLineLayout;
			global::Com.Syncfusion.Charts.Resource.Id.gridLinesLayout = global::XAM_Trial_1.Resource.Id.gridLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.iconView = global::XAM_Trial_1.Resource.Id.iconView;
			global::Com.Syncfusion.Charts.Resource.Id.label = global::XAM_Trial_1.Resource.Id.label;
			global::Com.Syncfusion.Charts.Resource.Id.legendHeader = global::XAM_Trial_1.Resource.Id.legendHeader;
			global::Com.Syncfusion.Charts.Resource.Id.legendItemsLayout = global::XAM_Trial_1.Resource.Id.legendItemsLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendLayout = global::XAM_Trial_1.Resource.Id.legendLayout;
			global::Com.Syncfusion.Charts.Resource.Id.legendScrollView = global::XAM_Trial_1.Resource.Id.legendScrollView;
			global::Com.Syncfusion.Charts.Resource.Id.legendViewGroup = global::XAM_Trial_1.Resource.Id.legendViewGroup;
			global::Com.Syncfusion.Charts.Resource.Id.rootLayout = global::XAM_Trial_1.Resource.Id.rootLayout;
			global::Com.Syncfusion.Charts.Resource.Id.seriesLayout = global::XAM_Trial_1.Resource.Id.seriesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.stripLinesLayout = global::XAM_Trial_1.Resource.Id.stripLinesLayout;
			global::Com.Syncfusion.Charts.Resource.Id.technicalIndicatorLayout = global::XAM_Trial_1.Resource.Id.technicalIndicatorLayout;
			global::Com.Syncfusion.Charts.Resource.Id.thumbLayout = global::XAM_Trial_1.Resource.Id.thumbLayout;
			global::Com.Syncfusion.Charts.Resource.Id.titleLayout = global::XAM_Trial_1.Resource.Id.titleLayout;
			global::Com.Syncfusion.Charts.Resource.Id.top_labels = global::XAM_Trial_1.Resource.Id.top_labels;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_layout = global::XAM_Trial_1.Resource.Layout.chart_layout;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend = global::XAM_Trial_1.Resource.Layout.chart_legend;
			global::Com.Syncfusion.Charts.Resource.Layout.chart_legend_item = global::XAM_Trial_1.Resource.Layout.chart_legend_item;
			global::Com.Syncfusion.Charts.Resource.Layout.range_navigator_layout = global::XAM_Trial_1.Resource.Layout.range_navigator_layout;
			global::Com.Syncfusion.Charts.Resource.String.q = global::XAM_Trial_1.Resource.String.q;
			global::Com.Syncfusion.Charts.Resource.String.quarter = global::XAM_Trial_1.Resource.String.quarter;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_close_label = global::XAM_Trial_1.Resource.String.sfchart_close_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_high_label = global::XAM_Trial_1.Resource.String.sfchart_high_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_low_label = global::XAM_Trial_1.Resource.String.sfchart_low_label;
			global::Com.Syncfusion.Charts.Resource.String.sfchart_open_label = global::XAM_Trial_1.Resource.String.sfchart_open_label;
			global::Com.Syncfusion.Charts.Resource.String.w = global::XAM_Trial_1.Resource.String.w;
			global::Com.Syncfusion.Charts.Resource.String.week = global::XAM_Trial_1.Resource.String.week;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int Fadein = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Fadeout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Scale_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Scale_out = 2131034115;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070002
			public const int accent = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int primary = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primaryDark = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int splash_background = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int window_background = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int splash_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splashscreen = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090022
			public const int account = 2131296290;
			
			// aapt resource value: 0x7f09000a
			public const int annotationLayout = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int axisLayout = 2131296263;
			
			// aapt resource value: 0x7f090012
			public const int big3 = 2131296274;
			
			// aapt resource value: 0x7f090036
			public const int bottom_labels = 2131296310;
			
			// aapt resource value: 0x7f090009
			public const int chartBehaviorLayout = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int chartLegendScrollView = 2131296269;
			
			// aapt resource value: 0x7f090037
			public const int content = 2131296311;
			
			// aapt resource value: 0x7f090005
			public const int dataMarkerLayout = 2131296261;
			
			// aapt resource value: 0x7f090015
			public const int djiaCurPrice = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int djiaNetChange = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int djiaPercentChange = 2131296279;
			
			// aapt resource value: 0x7f090014
			public const int djiaSpark = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int djiaTicker = 2131296275;
			
			// aapt resource value: 0x7f090002
			public const int gridLineLayout = 2131296258;
			
			// aapt resource value: 0x7f090038
			public const int gridLinesLayout = 2131296312;
			
			// aapt resource value: 0x7f090010
			public const int iconView = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int label = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int legendHeader = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int legendItemsLayout = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int legendLayout = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int legendScrollView = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int legendViewGroup = 2131296267;
			
			// aapt resource value: 0x7f09001a
			public const int nasdaqCurPrice = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int nasdaqNetChange = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int nasdaqPercentChange = 2131296284;
			
			// aapt resource value: 0x7f090019
			public const int nasdaqSpark = 2131296281;
			
			// aapt resource value: 0x7f090018
			public const int nasdaqTicker = 2131296280;
			
			// aapt resource value: 0x7f090029
			public const int pos1PerChange = 2131296297;
			
			// aapt resource value: 0x7f090028
			public const int pos1Ticker = 2131296296;
			
			// aapt resource value: 0x7f09002b
			public const int pos2PerChange = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int pos2Ticker = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int pos3PerChange = 2131296301;
			
			// aapt resource value: 0x7f09002c
			public const int pos3Ticker = 2131296300;
			
			// aapt resource value: 0x7f09002f
			public const int pos4PerChange = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int pos4Ticker = 2131296302;
			
			// aapt resource value: 0x7f090024
			public const int posChart = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int posNetProfit = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int posPercentProfit = 2131296294;
			
			// aapt resource value: 0x7f090023
			public const int position = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int positions = 2131296295;
			
			// aapt resource value: 0x7f090000
			public const int rootLayout = 2131296256;
			
			// aapt resource value: 0x7f090030
			public const int search = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int searchChange = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int searchChart = 2131296308;
			
			// aapt resource value: 0x7f090032
			public const int searchPrice = 2131296306;
			
			// aapt resource value: 0x7f090031
			public const int searchTicker = 2131296305;
			
			// aapt resource value: 0x7f090004
			public const int seriesLayout = 2131296260;
			
			// aapt resource value: 0x7f09001f
			public const int spCurPrice = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int spNetChange = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int spPercentChange = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int spSpark = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int spTicker = 2131296285;
			
			// aapt resource value: 0x7f090003
			public const int stripLinesLayout = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int technicalIndicatorLayout = 2131296262;
			
			// aapt resource value: 0x7f090039
			public const int thumbLayout = 2131296313;
			
			// aapt resource value: 0x7f090001
			public const int titleLayout = 2131296257;
			
			// aapt resource value: 0x7f090035
			public const int top_labels = 2131296309;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int chart_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int chart_legend = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int chart_legend_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int range_navigator_layout = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060008
			public const int app_name = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int default_search_ticker = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int q = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int quarter = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int sfchart_close_label = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int sfchart_high_label = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int sfchart_low_label = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int sfchart_open_label = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int w = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int week = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int MainTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int SplashBase = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int SplashTheme = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
